name: Build Multiplatform project
on:
  push:
    branches:
      - main
      - feature/ci_setup
  pull_request:
  workflow_dispatch:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-2022 ]
        gradle: [ 8.3 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ secrets.PACKAGE_USERNAME }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          ./gradlew assemble
          ./gradlew publishAllPublicationsToGitHubPackagesRepository
