name: Build Multiplatform project
on:
  push:
    branches:
      - main
      - feature/ci_setup
  pull_request:
  workflow_dispatch:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14 ]
        gradle: [ 8.3 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        run: |
          ./gradlew assemble
      - name: Publish
        shell: bash
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

